In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#neural network with 2 layers
#input dim: n
#hidden dim: h
#output dim: m
#weight names: W1, W2, b1, b2
#only forward pass, no backprop or optimization

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def initialize_parameters(n, h, m):
    W1 = np.random.randn(h, n) * 0.01
    b1 = np.zeros((h, 1))
    W2 = np.random.randn(m, h) * 0.01
    b2 = np.zeros((m, 1))
    return W1, b1, W2, b2

In [4]:
def forward_propagation(X, W1, b1, W2, b2):
    Z1 = np.dot(W1, X) + b1 #Pre-activation for hidden layer
    A1 = sigmoid(Z1) #Activation for hidden layer
    Z2 = np.dot(W2, A1) + b2 #Pre-activation for output layer
    A2 = sigmoid(Z2) #Activation for output layer
    return A2

In [5]:
n=3
h=4
m=2
W1, b1, W2, b2 = initialize_parameters(n, h, m)

In [6]:
X = np.array([[1], [2], [3]])
print(f"input: \n{X}")
print(f"\nW1: \n{W1}")
print(f"\nb1: \n{b1}")
print(f"\nW2: \n{W2}")
print(f"\nb2: \n{b2}")

A2 = forward_propagation(X, W1, b1, W2, b2)
print(f"\noutput: \n{A2}")

input: 
[[1]
 [2]
 [3]]

W1: 
[[ 0.00981303  0.01585497  0.01186899]
 [-0.00881274  0.00131904  0.01867075]
 [ 0.00370062 -0.01034216 -0.00856549]
 [-0.00361477  0.00362122  0.0183238 ]]

b1: 
[[0.]
 [0.]
 [0.]
 [0.]]

W2: 
[[ 0.00310995 -0.01212324  0.00416025  0.00622956]
 [-0.00467616 -0.01106564 -0.00118378  0.00604035]]

b2: 
[[0.]
 [0.]]

output: 
[[0.50016101]
 [0.49860763]]


In [9]:
class NeuralNetwork:
    def __init__(self, input_dim, hidden_dim, output_dim):
        self.W1 = np.random.randn(hidden_dim, input_dim) * 0.01
        self.b1 = np.zeros((hidden_dim, 1))
        self.W2 = np.random.randn(output_dim, hidden_dim) * 0.01
        self.b2 = np.zeros((output_dim, 1))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward_propagation(self, X):
        Z1 = np.dot(self.W1, X) + self.b1
        A1 = self.sigmoid(Z1)
        Z2 = np.dot(self.W2, A1) + self.b2
        A2 = self.sigmoid(Z2)
        return A2

# Example usage:    
nn = NeuralNetwork(n, h, m)
X = np.array([[1],
              [5],
              [3]])
A2 = nn.forward_propagation(X)
print(f"\noutput: \n{A2}")


output: 
[[0.50140531]
 [0.50022979]]
