In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#neural network with 2 layers
#input dim: n
#hidden dim: h
#output dim: m
#weight names: W1, W2, b1, b2
#only forward pass, no backprop or optimization

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def initialize_parameters(n, h, m):
    W1 = np.random.randn(h, n) * 0.01
    b1 = np.zeros((h, 1))
    W2 = np.random.randn(m, h) * 0.01
    b2 = np.zeros((m, 1))
    return W1, b1, W2, b2

In [4]:
def forward_propagation(X, W1, b1, W2, b2):
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    return A2

In [5]:
n=3
h=4
m=2
W1, b1, W2, b2 = initialize_parameters(n, h, m)

In [6]:
X = np.array([[1], [2], [3]])
print(f"input: \n{X}")
print(f"\nW1: \n{W1}")
print(f"\nb1: \n{b1}")
print(f"\nW2: \n{W2}")
print(f"\nb2: \n{b2}")

A2 = forward_propagation(X, W1, b1, W2, b2)
print(f"\noutput: \n{A2}")

input: 
[[1]
 [2]
 [3]]

W1: 
[[ 0.00872187 -0.00642343 -0.00828707]
 [-0.00257475 -0.00075582  0.0026696 ]
 [ 0.00834702  0.01073868  0.00547152]
 [ 0.00513007 -0.01896269  0.01181082]]

b1: 
[[0.]
 [0.]
 [0.]
 [0.]]

W2: 
[[-0.00425925  0.0099721   0.0095782  -0.00700058]
 [-0.01172937  0.00325412  0.02203171  0.01388054]]

b2: 
[[0.]
 [0.]]

output: 
[[0.50107299]
 [0.50351756]]


In [7]:
class NeuralNetwork:
    def __init__(self, input_dim, hidden_dim, output_dim):
        self.W1 = np.random.randn(hidden_dim, input_dim) * 0.01
        self.b1 = np.zeros((hidden_dim, 1))
        self.W2 = np.random.randn(output_dim, hidden_dim) * 0.01
        self.b2 = np.zeros((output_dim, 1))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward_propagation(self, X):
        Z1 = np.dot(self.W1, X) + self.b1
        A1 = self.sigmoid(Z1)
        Z2 = np.dot(self.W2, A1) + self.b2
        A2 = self.sigmoid(Z2)
        return A2

# Example usage:    
nn = NeuralNetwork(n, h, m)
X = np.array([[1], [2], [3]])
A2 = nn.forward_propagation(X)
print(f"\noutput: \n{A2}")


output: 
[[0.50064027]
 [0.49749162]]
